development:
  host: localhost
  adapter: postgresql
  database: getwhiteflame_development

staging:
  adapter: postgresql
  database: getwhiteflame_staging

production:
  adapter: postgresql
  database: getwhiteflame_production

test:
  host: localhost
  adapter: postgresql
  database: getwhiteflame_test